import Nav from '@/components/common/navigation/Nav';
import './globals.css';
import { Roboto, Tilt_Neon } from 'next/font/google';

import Footer from '@/components/common/navigation/Footer';

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['400', '500', '700', '900'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			{/* <body className={roboto.className}> */}
			<body>
				{/* <Nav /> */}
				{children}
				{/* <Footer /> */}
			</body>
		</html>
	);
}
